services:
  db:
    image: postgres:12
    container_name: ms-ecommerce-nest
    environment:
      POSTGRES_USER: ms-user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ms-product
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
